#pragma once

#include "CoreMinimal.h"

GUIYANGMAHJONG_API DECLARE_LOG_CATEGORY_EXTERN(LogMahjongServer, Log, All);
GUIYANGMAHJONG_API DECLARE_LOG_CATEGORY_EXTERN(LogMahjongNet, Log, All);
GUIYANGMAHJONG_API DECLARE_LOG_CATEGORY_EXTERN(LogMahjongRule, Log, All);
GUIYANGMAHJONG_API DECLARE_LOG_CATEGORY_EXTERN(LogMahjongScore, Log, All);
GUIYANGMAHJONG_API DECLARE_LOG_CATEGORY_EXTERN(LogMahjongUI, Log, All);
GUIYANGMAHJONG_API DECLARE_LOG_CATEGORY_EXTERN(LogMahjongAndroid, Log, All);
GUIYANGMAHJONG_API DECLARE_LOG_CATEGORY_EXTERN(LogMahjongReconnect, Log, All);
GUIYANGMAHJONG_API DECLARE_LOG_CATEGORY_EXTERN(LogMahjongMCP, Log, All);
